import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:geolocator/geolocator.dart';
import 'package:latlong2/latlong.dart';

import '../models/ors_route_result.dart';
import '../models/route.dart' as route_model;
import '../repositories/followed_route_repository.dart';
import 'route_follow_engine.dart';
import 'route_follow_guidance.dart';
import 'routing_service.dart';

/// What is being followed: a saved/community route or a route generated by
/// Search, reduced to the geometry and steps following needs.
class FollowTarget {
  final String id;
  final String startLabel;
  final String endLabel;
  final List<LatLng> path;
  final List<FollowStep> steps;

  /// Exactly one of these is set; used to reopen the right screen.
  final route_model.Route? route;
  final OrsRouteResult? generatedRoute;

  const FollowTarget._({
    required this.id,
    required this.startLabel,
    required this.endLabel,
    required this.path,
    required this.steps,
    this.route,
    this.generatedRoute,
  });

  /// [path] and [steps] are the geometry the route screen draws.
  factory FollowTarget.route(
    route_model.Route route, {
    required List<LatLng> path,
    required List<FollowStep> steps,
  }) {
    return FollowTarget._(
      id: route.id,
      startLabel: route.startLocation,
      endLabel: route.endLocation,
      path: path,
      steps: steps,
      route: route,
    );
  }

  factory FollowTarget.generated(
    OrsRouteResult result, {
    required String originName,
    required String destinationName,
  }) {
    return FollowTarget._(
      id: generatedId(result, originName, destinationName),
      startLabel: originName,
      endLabel: destinationName,
      path: result.polyline,
      steps: [
        for (final s in result.steps)
          FollowStep(
            mode: s.suggestedMode,
            startIndex: s.wayPointStart,
            endIndex: s.wayPointEnd,
          ),
      ],
      generatedRoute: result,
    );
  }

  static String generatedId(
    OrsRouteResult result,
    String originName,
    String destinationName,
  ) =>
      'generated|$originName|$destinationName|'
      '${result.distanceMeters.round()}|${result.polyline.length}';
}

/// Owns the in-progress "follow route" session: what is followed, the GPS
/// stream, progress along it, and guidance back to it. Living here rather
/// than in a screen means leaving the screen (e.g. via back) keeps tracking
/// and progress, and the session can be resumed from the persistent banner.
///
/// [notifyListeners] fires on session changes (start, stop, arrival);
/// per-fix updates and fetched walking paths go through [followUpdates] so
/// app-wide listeners such as the banner don't rebuild on every GPS fix.
class ActiveNavigationService extends ChangeNotifier {
  ActiveNavigationService._();
  static final ActiveNavigationService instance = ActiveNavigationService._();

  /// Fixes worse than this are dropped as outliers.
  static const maxAcceptedAccuracyMeters = 50.0;

  /// Shared stream settings for live location on the map screens.
  static LocationSettings get trackingSettings =>
      Platform.isAndroid
          ? AndroidSettings(
            accuracy: LocationAccuracy.best,
            distanceFilter: 3,
            intervalDuration: const Duration(milliseconds: 800),
          )
          : const LocationSettings(
            accuracy: LocationAccuracy.best,
            distanceFilter: 3,
          );

  /// Walking paths to the boarding/rejoin point are fetched at most this
  /// often, and only when the target or the traveler has moved this far.
  static const _connectorRefetchInterval = Duration(seconds: 20);
  static const _connectorRefetchMeters = 40.0;

  static const _distance = Distance();

  FollowTarget? _target;
  bool _enableRouteIntegrity = true;
  bool _showDownloadButton = true;
  RouteFollowEngine? _engine;
  StreamSubscription<Position>? _positionSubscription;
  Position? _lastPosition;
  Position? _previousPosition;
  FollowGuidance _guidance = FollowGuidance.none;

  List<LatLng>? _fetchedConnector;
  RouteFollowEngine? _fetchedConnectorEngine;
  LatLng? _fetchedConnectorTarget;
  List<LatLng>? _connector;
  double? _connectorRemainingMeters;
  bool _isFetchingConnector = false;
  DateTime? _lastConnectorRequestAt;
  int _sessionId = 0;
  bool _isSimulating = false;

  final _followTicks = _Ticker();

  /// Fires on every accepted fix and when a walking path arrives.
  Listenable get followUpdates => _followTicks;

  FollowTarget? get activeTarget => _target;
  route_model.Route? get activeRoute => _target?.route;
  bool get enableRouteIntegrity => _enableRouteIntegrity;
  bool get showDownloadButton => _showDownloadButton;
  bool get isActive => _target != null;
  bool isFollowing(String targetId) => _target?.id == targetId;

  Position? get lastPosition => _lastPosition;
  RouteFollowSnapshot? get followSnapshot => _engine?.lastSnapshot;
  bool get hasArrived => followSnapshot?.hasArrived ?? false;
  FollowGuidance get guidance => _guidance;

  /// Path to draw from the traveler to the guidance target: a walking route
  /// when one could be fetched, otherwise a straight line.
  List<LatLng>? get connectorPath => _connector;
  double? get connectorRemainingMeters => _connectorRemainingMeters;

  /// Off route and still working out the way back.
  bool get isRerouting =>
      _guidance.kind == FollowGuidanceKind.rejoin &&
      _isFetchingConnector &&
      _fetchedConnector == null;

  bool get isSimulating => _isSimulating;

  /// Starts following [target]. [initialPosition] seeds progress so the map
  /// is right before the next fix arrives.
  void start(
    FollowTarget target, {
    Position? initialPosition,
    bool enableRouteIntegrity = true,
    bool showDownloadButton = true,
  }) {
    _positionSubscription?.cancel();
    _positionSubscription = null;
    _sessionId++;
    _target = target;
    _enableRouteIntegrity = enableRouteIntegrity;
    _showDownloadButton = showDownloadButton;
    _engine = target.path.length >= 2 ? RouteFollowEngine(target.path) : null;
    _lastPosition = null;
    _previousPosition = null;
    _isSimulating = false;
    _resetGuidance();
    _rememberFollowedRoute(target);
    if (initialPosition != null) _ingest(initialPosition);

    if (!hasArrived) {
      _positionSubscription = Geolocator.getPositionStream(
        locationSettings: trackingSettings,
      ).listen(_onPosition, onError: (_) {});
    }
    notifyListeners();
  }

  /// Keeps the route on the device so it can be reopened offline from the
  /// offline routes list.
  void _rememberFollowedRoute(FollowTarget target) {
    final route = target.route;
    final generated = target.generatedRoute;
    final save =
        route != null
            ? FollowedRouteRepository.saveRoute(route)
            : FollowedRouteRepository.saveGenerated(
              target.id,
              generated!,
              originName: target.startLabel,
              destinationName: target.endLabel,
            );
    save.catchError((Object e) {
      debugPrint('ActiveNavigationService: could not save followed route: $e');
    });
  }

  void stop() {
    if (_target == null) return;
    _positionSubscription?.cancel();
    _positionSubscription = null;
    _sessionId++;
    _target = null;
    _engine = null;
    _lastPosition = null;
    _previousPosition = null;
    _isSimulating = false;
    _resetGuidance();
    notifyListeners();
  }

  /// Debug builds only: replace real GPS with simulated fixes, starting the
  /// trip over so earlier progress doesn't carry into the simulation.
  void beginSimulation() {
    final target = _target;
    if (!kDebugMode || target == null) return;
    _isSimulating = true;
    _positionSubscription?.pause();
    _sessionId++;
    _engine = target.path.length >= 2 ? RouteFollowEngine(target.path) : null;
    _lastPosition = null;
    _previousPosition = null;
    _resetGuidance();
    notifyListeners();
  }

  void feedSimulatedPosition(Position position) {
    if (!kDebugMode || !_isSimulating) return;
    _handleFix(position);
  }

  void endSimulation() {
    if (!_isSimulating) return;
    _isSimulating = false;
    if (_positionSubscription?.isPaused ?? false) {
      _positionSubscription!.resume();
    }
    notifyListeners();
  }

  void _onPosition(Position position) {
    if (_isSimulating) return;
    _handleFix(position);
  }

  void _handleFix(Position position) {
    final wasArrived = hasArrived;
    _ingest(position);
    if (!wasArrived && hasArrived) {
      // Nothing left to track; stop the GPS until the user finishes.
      _positionSubscription?.cancel();
      _positionSubscription = null;
      notifyListeners();
    }
  }

  void _ingest(Position position) {
    if (position.accuracy > maxAcceptedAccuracyMeters) return;
    _previousPosition = _lastPosition;
    _lastPosition = position;

    final engine = _engine;
    if (engine != null) {
      final snapshot = engine.update(
        LatLng(position.latitude, position.longitude),
        accuracyMeters: position.accuracy,
        at: position.timestamp,
      );
      _guidance = FollowGuidancePlanner.plan(
        engine: engine,
        snapshot: snapshot,
        steps: _target?.steps ?? const [],
        speedMps: _speedMps(position),
        now: position.timestamp,
      );
      engine.expectedJoinMeters =
          _guidance.target != null ? _guidance.targetAlongMeters : null;
      _updateConnector(LatLng(position.latitude, position.longitude));
    }
    _followTicks.tick();
  }

  /// GPS-reported speed, or speed between the last two fixes when the
  /// device doesn't report one.
  double _speedMps(Position position) {
    if (position.speed > 0) return position.speed;
    final previous = _previousPosition;
    if (previous == null) return 0;
    final seconds =
        position.timestamp.difference(previous.timestamp).inMilliseconds /
        1000.0;
    if (seconds <= 0) return 0;
    final meters = _distance.as(
      LengthUnit.Meter,
      LatLng(previous.latitude, previous.longitude),
      LatLng(position.latitude, position.longitude),
    );
    return meters / seconds;
  }

  void _resetGuidance() {
    _guidance = FollowGuidance.none;
    _fetchedConnector = null;
    _fetchedConnectorEngine = null;
    _fetchedConnectorTarget = null;
    _connector = null;
    _connectorRemainingMeters = null;
    _isFetchingConnector = false;
    _lastConnectorRequestAt = null;
  }

  void _updateConnector(LatLng position) {
    final target = _guidance.target;
    if (target == null) {
      _fetchedConnector = null;
      _fetchedConnectorEngine = null;
      _fetchedConnectorTarget = null;
      _connector = null;
      _connectorRemainingMeters = null;
      return;
    }

    // Keep using a fetched walking path while it still leads to the target
    // and the traveler is still on it.
    final fetchedEngine = _fetchedConnectorEngine;
    final fetchedTarget = _fetchedConnectorTarget;
    if (fetchedEngine != null && fetchedTarget != null) {
      final onPath = fetchedEngine.nearestInRange(
        position,
        0,
        fetchedEngine.totalMeters,
      );
      final targetMoved = _distance.as(LengthUnit.Meter, fetchedTarget, target);
      if (onPath != null &&
          onPath.distance <= _connectorRefetchMeters &&
          targetMoved <= _connectorRefetchMeters) {
        _connector = _fetchedConnector;
        _connectorRemainingMeters = fetchedEngine.totalMeters - onPath.along;
        return;
      }
      _fetchedConnector = null;
      _fetchedConnectorEngine = null;
      _fetchedConnectorTarget = null;
    }

    _connector = [position, target];
    _connectorRemainingMeters = _distance.as(
      LengthUnit.Meter,
      position,
      target,
    );
    _maybeFetchConnector(position, target);
  }

  void _maybeFetchConnector(LatLng from, LatLng to) {
    if (_isFetchingConnector) return;
    final last = _lastConnectorRequestAt;
    final now = DateTime.now();
    if (last != null && now.difference(last) < _connectorRefetchInterval) {
      return;
    }
    _isFetchingConnector = true;
    _lastConnectorRequestAt = now;
    final session = _sessionId;

    RoutingService.snapToRoad(origin: from, destination: to, mode: 'Walk')
        .then((result) {
          if (session != _sessionId) return;
          final path = result?.polyline;
          final current = _guidance.target;
          if (path == null || path.length < 2 || current == null) return;
          if (_distance.as(LengthUnit.Meter, current, to) >
              _connectorRefetchMeters) {
            return;
          }
          _fetchedConnector = path;
          _fetchedConnectorEngine = RouteFollowEngine(path);
          _fetchedConnectorTarget = to;
          final position = _lastPosition;
          if (position != null) {
            _updateConnector(LatLng(position.latitude, position.longitude));
          }
        })
        .catchError((_) {})
        .whenComplete(() {
          if (session != _sessionId) return;
          _isFetchingConnector = false;
          _followTicks.tick();
        });
  }
}

class _Ticker extends ChangeNotifier {
  void tick() => notifyListeners();
}
