import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:geolocator/geolocator.dart';
import 'package:latlong2/latlong.dart';
import 'package:permission_handler/permission_handler.dart';

import '../models/ors_route_result.dart';
import '../models/route.dart' as route_model;
import '../repositories/followed_route_repository.dart';
import 'follow_alert_notifier.dart';
import 'route_follow_engine.dart';
import 'route_follow_guidance.dart';
import 'routing_service.dart';

/// What is being followed: a saved/community route or a route generated by
/// Search, reduced to the geometry and steps following needs.
class FollowTarget {
  final String id;
  final String startLabel;
  final String endLabel;
  final List<LatLng> path;
  final List<FollowStep> steps;

  /// Exactly one of these is set; used to reopen the right screen.
  final route_model.Route? route;
  final OrsRouteResult? generatedRoute;

  const FollowTarget._({
    required this.id,
    required this.startLabel,
    required this.endLabel,
    required this.path,
    required this.steps,
    this.route,
    this.generatedRoute,
  });

  /// [path] and [steps] are the geometry the route screen draws.
  factory FollowTarget.route(
    route_model.Route route, {
    required List<LatLng> path,
    required List<FollowStep> steps,
  }) {
    return FollowTarget._(
      id: route.id,
      startLabel: route.startLocation,
      endLabel: route.endLocation,
      path: path,
      steps: steps,
      route: route,
    );
  }

  factory FollowTarget.generated(
    OrsRouteResult result, {
    required String originName,
    required String destinationName,
  }) {
    return FollowTarget._(
      id: generatedId(result, originName, destinationName),
      startLabel: originName,
      endLabel: destinationName,
      path: result.polyline,
      steps: [
        for (final s in result.steps)
          FollowStep(
            mode: s.suggestedMode,
            startIndex: s.wayPointStart,
            endIndex: s.wayPointEnd,
          ),
      ],
      generatedRoute: result,
    );
  }

  static String generatedId(
    OrsRouteResult result,
    String originName,
    String destinationName,
  ) =>
      'generated|$originName|$destinationName|'
      '${result.distanceMeters.round()}|${result.polyline.length}';
}

/// A stretch where the vehicle left the followed route and later came back
/// (or the trip ended first), with the path it actually took. Kept on the
/// device only; the rider can offer it as a correction afterwards.
class RideDeviation {
  /// Distance along the route where the vehicle left it.
  final double fromMeters;

  /// Where it rejoined; null when the trip ended before rejoining.
  final double? toMeters;
  final List<LatLng> points;
  final double lengthMeters;

  const RideDeviation({
    required this.fromMeters,
    required this.toMeters,
    required this.points,
    required this.lengthMeters,
  });
}

/// Owns the in-progress "follow route" session: what is followed, the GPS
/// stream, progress along it, and guidance back to it. Living here rather
/// than in a screen means leaving the screen (e.g. via back) keeps tracking
/// and progress, and the session can be resumed from the persistent banner.
///
/// [notifyListeners] fires on session changes (start, stop, arrival);
/// per-fix updates and fetched walking paths go through [followUpdates] so
/// app-wide listeners such as the banner don't rebuild on every GPS fix.
class ActiveNavigationService extends ChangeNotifier {
  ActiveNavigationService._();
  static final ActiveNavigationService instance = ActiveNavigationService._();

  /// Fixes worse than this are dropped as outliers.
  static const maxAcceptedAccuracyMeters = 50.0;

  /// Shared stream settings for live location on the map screens.
  static LocationSettings get trackingSettings =>
      Platform.isAndroid
          ? AndroidSettings(
            accuracy: LocationAccuracy.best,
            distanceFilter: 3,
            intervalDuration: const Duration(milliseconds: 800),
          )
          : const LocationSettings(
            accuracy: LocationAccuracy.best,
            distanceFilter: 3,
          );

  /// Stream settings for a follow session. On Android, geolocator runs this
  /// stream as a location foreground service with an ongoing notification,
  /// so tracking continues while the app is in the background. It needs
  /// only while-in-use location permission, since it is started from the
  /// foreground when the user taps Start.
  static LocationSettings _followSettings(FollowTarget target) =>
      Platform.isAndroid
          ? AndroidSettings(
            accuracy: LocationAccuracy.best,
            distanceFilter: 3,
            intervalDuration: const Duration(milliseconds: 800),
            foregroundNotificationConfig: ForegroundNotificationConfig(
              notificationTitle:
                  'Following: ${target.startLabel} → ${target.endLabel}',
              notificationText:
                  'TransitPH is tracking your trip along this route.',
              notificationChannelName: 'Follow Route',
              notificationIcon: const AndroidResource(
                name: FollowAlertNotifier.statusIcon,
                defType: 'drawable',
              ),
              setOngoing: true,
              // Keeps fixes flowing with the screen off; held only while a
              // route is followed and released on stop, arrival or idle.
              enableWakeLock: true,
            ),
          )
          : trackingSettings;

  /// Tracking pauses itself after this long without real movement, to save
  /// battery when a session is left running by mistake.
  static const _idleTimeout = Duration(minutes: 30);
  static const _idleMoveMeters = 100.0;

  /// Walking paths to the boarding/rejoin point are fetched at most this
  /// often, and only when the target or the traveler has moved this far.
  static const _connectorRefetchInterval = Duration(seconds: 20);
  static const _connectorRefetchMeters = 40.0;

  static const _distance = Distance();

  FollowTarget? _target;
  bool _enableRouteIntegrity = true;
  bool _showDownloadButton = true;
  RouteFollowEngine? _engine;
  StreamSubscription<Position>? _positionSubscription;
  Position? _lastPosition;
  Position? _previousPosition;
  FollowGuidance _guidance = FollowGuidance.none;

  List<LatLng>? _fetchedConnector;
  RouteFollowEngine? _fetchedConnectorEngine;
  LatLng? _fetchedConnectorTarget;
  List<LatLng>? _connector;
  double? _connectorRemainingMeters;
  bool _isFetchingConnector = false;
  DateTime? _lastConnectorRequestAt;
  int _sessionId = 0;
  bool _isSimulating = false;

  /// Off-route stretches shorter than this, or not at vehicle speed, are
  /// noise or the rider walking — not a different way the vehicle goes.
  static const _minDeviationMeters = 300.0;
  static const _traceSpacingMeters = 10.0;

  List<LatLng>? _detourTrace;
  double _detourFromMeters = 0;
  final List<double> _detourSpeeds = [];
  final List<RideDeviation> _deviations = [];

  Timer? _idleTimer;
  LatLng? _idleAnchor;
  DateTime _lastMovedAt = DateTime.now();
  bool _isPausedForIdle = false;

  final _followTicks = _Ticker();

  /// Fires on every accepted fix and when a walking path arrives.
  Listenable get followUpdates => _followTicks;

  FollowTarget? get activeTarget => _target;
  route_model.Route? get activeRoute => _target?.route;
  bool get enableRouteIntegrity => _enableRouteIntegrity;
  bool get showDownloadButton => _showDownloadButton;
  bool get isActive => _target != null;
  bool isFollowing(String targetId) => _target?.id == targetId;

  Position? get lastPosition => _lastPosition;
  RouteFollowSnapshot? get followSnapshot => _engine?.lastSnapshot;
  bool get hasArrived => followSnapshot?.hasArrived ?? false;
  FollowGuidance get guidance => _guidance;

  /// Path to draw from the traveler to the guidance target: a walking route
  /// when one could be fetched, otherwise a straight line.
  List<LatLng>? get connectorPath => _connector;
  double? get connectorRemainingMeters => _connectorRemainingMeters;

  /// Off route and still working out the way back.
  bool get isRerouting =>
      _guidance.kind == FollowGuidanceKind.rejoin &&
      _isFetchingConnector &&
      _fetchedConnector == null;

  bool get isSimulating => _isSimulating;

  /// Tracking was paused after a long time without movement; reopening the
  /// route resumes it ([resumeTracking]).
  bool get isPausedForIdle => _isPausedForIdle;

  /// The path the vehicle is taking while it is off the route, for drawing.
  List<LatLng>? get detourPath =>
      _guidance.kind == FollowGuidanceKind.vehicleDetour ? _detourTrace : null;

  /// Ends any open off-route stretch and returns this session's deviations.
  /// Call before [stop], which clears them.
  List<RideDeviation> finishDeviations() {
    _closeDeviation(rejoinedAt: null, rejoinPoint: null);
    return List.unmodifiable(_deviations);
  }

  /// Starts following [target]. [initialPosition] seeds progress so the map
  /// is right before the next fix arrives.
  void start(
    FollowTarget target, {
    Position? initialPosition,
    bool enableRouteIntegrity = true,
    bool showDownloadButton = true,
  }) {
    _stopTracking();
    _sessionId++;
    _target = target;
    _enableRouteIntegrity = enableRouteIntegrity;
    _showDownloadButton = showDownloadButton;
    _engine = target.path.length >= 2 ? RouteFollowEngine(target.path) : null;
    _lastPosition = null;
    _previousPosition = null;
    _isSimulating = false;
    _isPausedForIdle = false;
    _resetGuidance();
    _rememberFollowedRoute(target);
    if (initialPosition != null) _ingest(initialPosition);

    if (!hasArrived) {
      _requestNotificationPermission();
      _startTracking();
    }
    notifyListeners();
  }

  /// Resumes a session paused for being idle.
  void resumeTracking() {
    if (!_isPausedForIdle || _target == null || hasArrived) return;
    _isPausedForIdle = false;
    _startTracking();
    notifyListeners();
  }

  void _startTracking() {
    final target = _target;
    if (target == null) return;
    _positionSubscription?.cancel();
    _positionSubscription = Geolocator.getPositionStream(
      locationSettings: _followSettings(target),
    ).listen(_onPosition, onError: (_) {});
    _idleAnchor = null;
    _lastMovedAt = DateTime.now();
    _idleTimer?.cancel();
    _idleTimer = Timer.periodic(const Duration(minutes: 1), (_) => _checkIdle());
  }

  void _stopTracking() {
    _positionSubscription?.cancel();
    _positionSubscription = null;
    _idleTimer?.cancel();
    _idleTimer = null;
  }

  void _checkIdle() {
    if (_isSimulating || hasArrived || _positionSubscription == null) return;
    if (DateTime.now().difference(_lastMovedAt) < _idleTimeout) return;
    _stopTracking();
    _isPausedForIdle = true;
    notifyListeners();
  }

  /// Android 13+ hides the tracking notification without this; tracking
  /// itself works either way.
  void _requestNotificationPermission() {
    if (!Platform.isAndroid) return;
    Permission.notification.status
        .then((status) {
          if (status.isDenied) return Permission.notification.request();
          return status;
        })
        .catchError((Object _) => PermissionStatus.denied);
  }

  /// Keeps the route on the device so it can be reopened offline from the
  /// offline routes list.
  void _rememberFollowedRoute(FollowTarget target) {
    final route = target.route;
    final generated = target.generatedRoute;
    final save =
        route != null
            ? FollowedRouteRepository.saveRoute(route)
            : FollowedRouteRepository.saveGenerated(
              target.id,
              generated!,
              originName: target.startLabel,
              destinationName: target.endLabel,
            );
    save.catchError((Object e) {
      debugPrint('ActiveNavigationService: could not save followed route: $e');
    });
  }

  void stop() {
    if (_target == null) return;
    _stopTracking();
    _sessionId++;
    _target = null;
    _engine = null;
    _lastPosition = null;
    _previousPosition = null;
    _isSimulating = false;
    _isPausedForIdle = false;
    _resetGuidance();
    notifyListeners();
  }

  /// Debug builds only: replace real GPS with simulated fixes, starting the
  /// trip over so earlier progress doesn't carry into the simulation.
  void beginSimulation() {
    final target = _target;
    if (!kDebugMode || target == null) return;
    _isSimulating = true;
    _positionSubscription?.pause();
    _sessionId++;
    _engine = target.path.length >= 2 ? RouteFollowEngine(target.path) : null;
    _lastPosition = null;
    _previousPosition = null;
    _resetGuidance();
    notifyListeners();
  }

  void feedSimulatedPosition(Position position) {
    if (!kDebugMode || !_isSimulating) return;
    _handleFix(position);
  }

  void endSimulation() {
    if (!_isSimulating) return;
    _isSimulating = false;
    _lastMovedAt = DateTime.now();
    if (_positionSubscription?.isPaused ?? false) {
      _positionSubscription!.resume();
    }
    notifyListeners();
  }

  void _onPosition(Position position) {
    if (_isSimulating) return;
    _handleFix(position);
  }

  void _handleFix(Position position) {
    final wasArrived = hasArrived;
    _ingest(position);
    if (!wasArrived && hasArrived) {
      // Nothing left to track; stop the GPS until the user finishes.
      _stopTracking();
      final inBackground =
          WidgetsBinding.instance.lifecycleState != AppLifecycleState.resumed;
      final target = _target;
      if (inBackground && target != null) {
        FollowAlertNotifier.showArrived(target.endLabel);
      }
      notifyListeners();
    }
  }

  void _ingest(Position position) {
    if (position.accuracy > maxAcceptedAccuracyMeters) return;
    _previousPosition = _lastPosition;
    _lastPosition = position;

    final here = LatLng(position.latitude, position.longitude);
    final anchor = _idleAnchor;
    if (anchor == null ||
        _distance.as(LengthUnit.Meter, anchor, here) > _idleMoveMeters) {
      _idleAnchor = here;
      _lastMovedAt = DateTime.now();
    }

    final engine = _engine;
    if (engine != null) {
      final snapshot = engine.update(
        LatLng(position.latitude, position.longitude),
        accuracyMeters: position.accuracy,
        at: position.timestamp,
      );
      _guidance = FollowGuidancePlanner.plan(
        engine: engine,
        snapshot: snapshot,
        steps: _target?.steps ?? const [],
        speedMps: _speedMps(position),
        now: position.timestamp,
      );
      engine.expectedJoinMeters =
          _guidance.target != null ? _guidance.targetAlongMeters : null;
      _updateConnector(LatLng(position.latitude, position.longitude));
      _trackDeviation(snapshot, here, _speedMps(position));
    }
    _followTicks.tick();
  }

  /// Records the path taken while off the route; when the vehicle rejoins
  /// (or arrives), keeps it as a [RideDeviation] if it was a real ride.
  void _trackDeviation(RouteFollowSnapshot snapshot, LatLng here, double speed) {
    if (!snapshot.hasProgress) return;
    if (snapshot.status == RouteFollowStatus.awayFromRoute) {
      final trace = _detourTrace ??= [snapshot.progressPoint];
      if (trace.length == 1) {
        _detourFromMeters = snapshot.progressMeters;
        _detourSpeeds.clear();
      }
      if (_distance.as(LengthUnit.Meter, trace.last, here) >=
          _traceSpacingMeters) {
        trace.add(here);
      }
      _detourSpeeds.add(speed);
    } else if (_detourTrace != null) {
      _closeDeviation(
        rejoinedAt: snapshot.progressMeters,
        rejoinPoint: snapshot.progressPoint,
      );
    }
  }

  void _closeDeviation({double? rejoinedAt, LatLng? rejoinPoint}) {
    final trace = _detourTrace;
    _detourTrace = null;
    if (trace == null || trace.length < 2) return;
    final points = [...trace, if (rejoinPoint != null) rejoinPoint];
    var length = 0.0;
    for (var i = 1; i < points.length; i++) {
      length += _distance.as(LengthUnit.Meter, points[i - 1], points[i]);
    }
    final speeds = [..._detourSpeeds]..sort();
    final medianSpeed = speeds.isEmpty ? 0.0 : speeds[speeds.length ~/ 2];
    if (length < _minDeviationMeters ||
        medianSpeed < FollowGuidancePlanner.vehicleSpeedMps) {
      return;
    }
    _deviations.add(
      RideDeviation(
        fromMeters: _detourFromMeters,
        toMeters: rejoinedAt,
        points: points,
        lengthMeters: length,
      ),
    );
  }

  /// GPS-reported speed, or speed between the last two fixes when the
  /// device doesn't report one.
  double _speedMps(Position position) {
    if (position.speed > 0) return position.speed;
    final previous = _previousPosition;
    if (previous == null) return 0;
    final seconds =
        position.timestamp.difference(previous.timestamp).inMilliseconds /
        1000.0;
    if (seconds <= 0) return 0;
    final meters = _distance.as(
      LengthUnit.Meter,
      LatLng(previous.latitude, previous.longitude),
      LatLng(position.latitude, position.longitude),
    );
    return meters / seconds;
  }

  void _resetGuidance() {
    _guidance = FollowGuidance.none;
    _fetchedConnector = null;
    _fetchedConnectorEngine = null;
    _fetchedConnectorTarget = null;
    _connector = null;
    _connectorRemainingMeters = null;
    _isFetchingConnector = false;
    _lastConnectorRequestAt = null;
    _detourTrace = null;
    _detourSpeeds.clear();
    _deviations.clear();
  }

  void _updateConnector(LatLng position) {
    final target = _guidance.target;
    if (target == null) {
      _fetchedConnector = null;
      _fetchedConnectorEngine = null;
      _fetchedConnectorTarget = null;
      _connector = null;
      _connectorRemainingMeters = null;
      return;
    }

    // Keep using a fetched walking path while it still leads to the target
    // and the traveler is still on it.
    final fetchedEngine = _fetchedConnectorEngine;
    final fetchedTarget = _fetchedConnectorTarget;
    if (fetchedEngine != null && fetchedTarget != null) {
      final onPath = fetchedEngine.nearestInRange(
        position,
        0,
        fetchedEngine.totalMeters,
      );
      final targetMoved = _distance.as(LengthUnit.Meter, fetchedTarget, target);
      if (onPath != null &&
          onPath.distance <= _connectorRefetchMeters &&
          targetMoved <= _connectorRefetchMeters) {
        _connector = _fetchedConnector;
        _connectorRemainingMeters = fetchedEngine.totalMeters - onPath.along;
        return;
      }
      _fetchedConnector = null;
      _fetchedConnectorEngine = null;
      _fetchedConnectorTarget = null;
    }

    _connector = [position, target];
    _connectorRemainingMeters = _distance.as(
      LengthUnit.Meter,
      position,
      target,
    );
    _maybeFetchConnector(position, target);
  }

  void _maybeFetchConnector(LatLng from, LatLng to) {
    if (_isFetchingConnector) return;
    final last = _lastConnectorRequestAt;
    final now = DateTime.now();
    if (last != null && now.difference(last) < _connectorRefetchInterval) {
      return;
    }
    _isFetchingConnector = true;
    _lastConnectorRequestAt = now;
    final session = _sessionId;

    RoutingService.snapToRoad(origin: from, destination: to, mode: 'Walk')
        .then((result) {
          if (session != _sessionId) return;
          final path = result?.polyline;
          final current = _guidance.target;
          if (path == null || path.length < 2 || current == null) return;
          if (_distance.as(LengthUnit.Meter, current, to) >
              _connectorRefetchMeters) {
            return;
          }
          _fetchedConnector = path;
          _fetchedConnectorEngine = RouteFollowEngine(path);
          _fetchedConnectorTarget = to;
          final position = _lastPosition;
          if (position != null) {
            _updateConnector(LatLng(position.latitude, position.longitude));
          }
        })
        .catchError((_) {})
        .whenComplete(() {
          if (session != _sessionId) return;
          _isFetchingConnector = false;
          _followTicks.tick();
        });
  }
}

class _Ticker extends ChangeNotifier {
  void tick() => notifyListeners();
}
