import 'package:latlong2/latlong.dart';

import '../models/ors_route_result.dart';
import '../models/route.dart' as route_model;
import 'active_navigation_service.dart';
import 'route_follow_engine.dart';

/// Snaps a ridden path to roads; returns null to use the raw points.
typedef RideSnapper = Future<List<LatLng>?> Function(List<LatLng> points);

/// Turns the ways a vehicle actually went (recorded while following) into a
/// route draft: the followed route with each deviated stretch replaced by
/// the path the ride took. The rider reviews and adjusts the draft in the
/// editor before anything is submitted.
class RideCorrection {
  /// [path] and [stepBoundaries] are the geometry that was followed (the
  /// end index of each step in [path]).
  static Future<({List<LatLng> path, List<int> boundaries, Set<int> changed})>
  splice({
    required List<LatLng> path,
    required List<int> stepBoundaries,
    required List<RideDeviation> deviations,
    required RideSnapper snap,
  }) async {
    var newPath = List<LatLng>.of(path);
    var boundaries = List<int>.of(stepBoundaries);
    final changed = <int>{};

    // Latest first, so earlier stretches' distances along the route stay
    // valid (only later parts of the path have been replaced so far).
    final ordered = [...deviations]
      ..sort((a, b) => b.fromMeters.compareTo(a.fromMeters));
    for (final deviation in ordered) {
      if (newPath.length < 2) break;
      final line = RouteFollowEngine(newPath);
      final rejoins = deviation.toMeters != null;
      final from = deviation.fromMeters;
      final to = deviation.toMeters ?? line.totalMeters;
      if (to <= from) continue;

      final a = line.segmentAt(from);
      final b = line.segmentAt(to);
      final ridden = await snap(deviation.points) ?? deviation.points;
      final middle = [
        line.pointAt(from),
        ...ridden,
        if (rejoins) line.pointAt(to),
      ];
      final tail = rejoins ? newPath.sublist(b + 1) : const <LatLng>[];
      newPath = [...newPath.sublist(0, a + 1), ...middle, ...tail];

      // Vertices a+1..b were replaced by [middle].
      final delta = middle.length - (b - a);
      final last = newPath.length - 1;
      boundaries = [
        for (var i = 0; i < boundaries.length; i++)
          () {
            final k = boundaries[i];
            final start = i == 0 ? 0 : boundaries[i - 1];
            if (k > a && start <= b) changed.add(i);
            if (k <= a) return k;
            if (k > b && rejoins) return (k + delta).clamp(0, last);
            return (a + middle.length).clamp(0, last);
          }(),
      ];
    }
    if (boundaries.isNotEmpty) boundaries[boundaries.length - 1] = newPath.length - 1;
    return (path: newPath, boundaries: boundaries, changed: changed);
  }

  /// A draft of [route] with the ride's deviations applied. Steps whose line
  /// changed lose their saved control points (the editor re-derives them).
  static Future<route_model.Route> draftFromRoute({
    required route_model.Route route,
    required List<LatLng> followedPath,
    required List<int> stepBoundaries,
    required List<RideDeviation> deviations,
    required RideSnapper snap,
  }) async {
    final steps =
        route.steps.isNotEmpty
            ? route.steps
            : [
              route_model.Step(mode: 'Jeepney', instruction: '', details: ''),
            ];
    final result = await splice(
      path: followedPath,
      stepBoundaries: stepBoundaries,
      deviations: deviations,
      snap: snap,
    );
    return _draft(
      startLocation: route.startLocation,
      endLocation: route.endLocation,
      description: route.shortDescription,
      audienceTags: route.audienceTags,
      steps: [
        for (var i = 0; i < steps.length; i++)
          result.changed.contains(i)
              ? steps[i].copyWith(controlPoints: const [])
              : steps[i],
      ],
      path: result.path,
      boundaries: result.boundaries,
    );
  }

  /// A draft from a route generated by Search, with the ride applied.
  static Future<route_model.Route> draftFromGenerated({
    required OrsRouteResult generated,
    required String originName,
    required String destinationName,
    required List<RideDeviation> deviations,
    required RideSnapper snap,
  }) async {
    final path = generated.polyline;
    var steps = <route_model.Step>[];
    var boundaries = <int>[];
    var previous = 0;
    for (final s in generated.steps) {
      if (s.wayPointEnd <= previous || s.wayPointEnd >= path.length) continue;
      steps.add(
        route_model.Step(
          mode: s.suggestedMode,
          instruction: s.instruction,
          details: '',
          actualFare: s.estimatedFare > 0 ? s.estimatedFare : null,
        ),
      );
      boundaries.add(s.wayPointEnd);
      previous = s.wayPointEnd;
    }
    if (steps.isEmpty) {
      steps = [route_model.Step(mode: 'Jeepney', instruction: '', details: '')];
      boundaries = [path.length - 1];
    }
    boundaries[boundaries.length - 1] = path.length - 1;

    final result = await splice(
      path: path,
      stepBoundaries: boundaries,
      deviations: deviations,
      snap: snap,
    );
    return _draft(
      startLocation: originName,
      endLocation: destinationName,
      description: '',
      audienceTags: const [],
      steps: steps,
      path: result.path,
      boundaries: result.boundaries,
    );
  }

  static route_model.Route _draft({
    required String startLocation,
    required String endLocation,
    required String description,
    required List<String> audienceTags,
    required List<route_model.Step> steps,
    required List<LatLng> path,
    required List<int> boundaries,
  }) {
    // Steps left with no line (the trip ended off the route before them)
    // are dropped; the last kept step runs to the end of the ride.
    final keptSteps = <route_model.Step>[];
    final keptBoundaries = <int>[];
    var previous = 0;
    for (var i = 0; i < steps.length && i < boundaries.length; i++) {
      if (boundaries[i] <= previous) continue;
      keptSteps.add(steps[i]);
      keptBoundaries.add(boundaries[i]);
      previous = boundaries[i];
    }
    if (keptSteps.isEmpty && steps.isNotEmpty) {
      keptSteps.add(steps.first);
      keptBoundaries.add(path.length - 1);
    }
    if (keptBoundaries.isNotEmpty) {
      keptBoundaries[keptBoundaries.length - 1] = path.length - 1;
    }

    return route_model.Route(
      id: '',
      startLocation: startLocation,
      endLocation: endLocation,
      shortDescription: description,
      steps: keptSteps,
      pathPoints: path,
      stepBoundaries: keptBoundaries,
      startLat: path.first.latitude,
      startLng: path.first.longitude,
      endLat: path.last.latitude,
      endLng: path.last.longitude,
      audienceTags: audienceTags,
    );
  }
}
