// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDblTjuOfpPL3ReEm1z8ymaig3Pg7PnnXU',
    appId: '1:617760269760:web:a773cbd4580d0fb3101425',
    messagingSenderId: '617760269760',
    projectId: 'transitph-75da4',
    authDomain: 'transitph-75da4.firebaseapp.com',
    storageBucket: 'transitph-75da4.firebasestorage.app',
    measurementId: 'G-F3LWNTC73W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkzHUPwhy6QObhIYApZANp1ohUFHrMCZ0',
    appId: '1:617760269760:android:2b1affdb8844f6bf101425',
    messagingSenderId: '617760269760',
    projectId: 'transitph-75da4',
    storageBucket: 'transitph-75da4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ttEddxVIP5e09rMQTmPFQhGXWNrc814',
    appId: '1:617760269760:ios:aad28bcb757e723f101425',
    messagingSenderId: '617760269760',
    projectId: 'transitph-75da4',
    storageBucket: 'transitph-75da4.firebasestorage.app',
    iosBundleId: 'com.example.transitphBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ttEddxVIP5e09rMQTmPFQhGXWNrc814',
    appId: '1:617760269760:ios:aad28bcb757e723f101425',
    messagingSenderId: '617760269760',
    projectId: 'transitph-75da4',
    storageBucket: 'transitph-75da4.firebasestorage.app',
    iosBundleId: 'com.example.transitphBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDblTjuOfpPL3ReEm1z8ymaig3Pg7PnnXU',
    appId: '1:617760269760:web:4c273af4257d7179101425',
    messagingSenderId: '617760269760',
    projectId: 'transitph-75da4',
    authDomain: 'transitph-75da4.firebaseapp.com',
    storageBucket: 'transitph-75da4.firebasestorage.app',
    measurementId: 'G-KLJLR1TYWL',
  );
}
